#!/bin/bash

# ImageKit Upload Script
# This script helps upload landing page images to ImageKit

echo "🚀 ImageKit Upload Guide"
echo "========================"
echo ""
echo "STEP 1: Install ImageKit CLI (if not installed)"
echo "npm install -g imagekit-cli"
echo ""
echo "STEP 2: Configure ImageKit"
echo "imagekit configure"
echo "  URL Endpoint: https://ik.imagekit.io/onelove431212341234"
echo "  Public Key: public_QdLLjPTKH/+dRHxXqo0lSiOs310="
echo "  Private Key: private_3aE43Ff8Wh96MBV47ri3Jp2zsIA="
echo ""
echo "STEP 3: Upload images"
echo ""
echo "Images to upload:"
echo "1. landing-young-professional.png (587 KB)"
echo "2. landing-elderly-woman.png (612 KB)"
echo "3. landing-spice-shop.png (572 KB)"
echo "4. landing-business-ecosystem.png (615 KB)"
echo "5. ai-chatbot-store.png (1.6 MB)"
echo "6. works-24-7.png (329 KB)"
echo "7. whatsapp-ready.png (175 KB)"
echo "8. any-device.png (138 KB)"
echo "9. storehouse-logo-new.png (655 KB)"
echo ""
echo "Upload command:"
echo "imagekit upload public/landing-young-professional.png --name landing-young-professional.png"
echo ""
echo "Or bulk upload:"
echo "cd public && for img in landing-*.png ai-chatbot-store.png works-24-7.png whatsapp-ready.png any-device.png storehouse-logo-new.png; do imagekit upload \$img --name \$img; done"
echo ""
echo "✅ After upload, images will be available at:"
echo "https://ik.imagekit.io/onelove431212341234/[filename]"
