import React, { Suspense, useState, useEffect } from 'react';
import { ErrorBoundary } from '../components/ErrorBoundary';
import BusinessSettings from '../components/BusinessSettings';
import { getItems, getSales, getSettings } from '../db/idb';
import '../App.css';

const LoadingFallback = () => (
  <div style={{
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    color: '#6b7280'
  }}>
    Loading Settings...
  </div>
);

export default function Settings() {
  const [showEODModal, setShowEODModal] = useState(false);
  const [eodFormat, setEodFormat] = useState('readable');
  const [items, setItems] = useState([]);
  const [sales, setSales] = useState([]);
  const [settings, setSettings] = useState({});

  // Load data from IndexedDB when EOD modal opens
  useEffect(() => {
    if (showEODModal) {
      loadData();
    }
  }, [showEODModal]);

  const loadData = async () => {
    try {
      const [itemsData, salesData, settingsData] = await Promise.all([
        getItems(),
        getSales(),
        getSettings()
      ]);
      setItems(itemsData || []);
      setSales(salesData || []);
      setSettings(settingsData || {});
    } catch (error) {
      console.error('[Settings] Error loading data:', error);
    }
  };

  const generateEODReport = (format = 'readable') => {
    const today = new Date();
    const dateStr = today.toLocaleDateString('en-NG');

    // Calculate today's stats
    const todaySales = sales.filter(sale => {
      const saleDate = new Date(sale.timestamp).toDateString();
      return saleDate === today.toDateString();
    });

    const todayStats = {
      total: 0,
      profit: 0,
      cash: 0,
      credit: 0,
      transactions: todaySales.length
    };

    todaySales.forEach(sale => {
      todayStats.total += sale.total || 0;
      const item = items.find(i => i.name === sale.itemName);
      if (item) {
        const profit = (sale.sellPrice - item.purchasePrice) * sale.qty;
        todayStats.profit += profit;
      }
      if (sale.paymentMethod === 'cash') {
        todayStats.cash += sale.total || 0;
      } else if (sale.paymentMethod === 'credit') {
        todayStats.credit += sale.total || 0;
      }
    });

    // Find top selling item
    const itemSales = {};
    todaySales.forEach(sale => {
      if (!itemSales[sale.itemName]) {
        itemSales[sale.itemName] = { qty: 0, profit: 0 };
      }
      itemSales[sale.itemName].qty += sale.qty;
      const item = items.find(i => i.name === sale.itemName);
      if (item) {
        itemSales[sale.itemName].profit += (sale.sellPrice - item.purchasePrice) * sale.qty;
      }
    });

    const topItem = Object.entries(itemSales).sort((a, b) => b[1].profit - a[1].profit)[0];
    const topItemName = topItem ? topItem[0] : 'N/A';
    const topItemQty = topItem ? topItem[1].qty : 0;
    const topItemProfit = topItem ? topItem[1].profit : 0;

    // Count low stock items
    const lowStockItems = items.filter(item => item.qty <= (item.lowStockThreshold || 5));

    if (format === 'readable') {
      return `📊 Storehouse Daily Report
📅 ${dateStr} | 🏪 ${settings.businessName || 'My Business'}
💰 Sales: ₦${todayStats.total.toLocaleString()} | ✨ Profit: ₦${todayStats.profit.toLocaleString()} (${todayStats.total ? ((todayStats.profit/todayStats.total)*100).toFixed(1) : 0}%)
💵 Cash: ₦${todayStats.cash.toLocaleString()} | 📝 Credit: ₦${todayStats.credit.toLocaleString()}
📦 Transactions: ${todayStats.transactions}
🏆 Top: ${topItemName} - ${topItemQty} units (₦${topItemProfit.toLocaleString()} profit)
⚠️ Low Stock: ${lowStockItems.length} items
Generated by Storehouse 📱`;
    } else {
      return `=== Storehouse EOD ===
Date: ${today.toISOString().split('T')[0]}
Sales: ₦${todayStats.total.toLocaleString()} | Profit: ₦${todayStats.profit.toLocaleString()}
Cash: ₦${todayStats.cash.toLocaleString()} | Credit: ₦${todayStats.credit.toLocaleString()}
Transactions: ${todayStats.transactions} | Top: ${topItemName}
Low Stock: ${lowStockItems.length}
======================`;
    }
  };

  const handleSendEOD = () => {
    const message = generateEODReport(eodFormat);
    const encodedMessage = encodeURIComponent(message);
    window.open(`https://wa.me/?text=${encodedMessage}`, '_blank');
    setShowEODModal(false);
  };

  const handleOpenEODModal = () => {
    console.log('[Settings] EOD Report triggered');
    setShowEODModal(true);
  };

  const handleExportCSV = () => {
    console.log('[Settings] Export CSV triggered');
    alert('Export CSV functionality - integrate with your export logic');
  };

  return (
    <ErrorBoundary>
      <Suspense fallback={<LoadingFallback />}>
        <BusinessSettings
          isOpen={true}
          onClose={() => window.history.back()}
          onSendEOD={handleOpenEODModal}
          onExportCSV={handleExportCSV}
          onToast={(message) => console.log('[Settings Toast]', message)}
        />

        {/* EOD Report Modal */}
        {showEODModal && (
          <div className="modal-overlay" onClick={() => setShowEODModal(false)}>
            <div className="modal eod-modal" onClick={(e) => e.stopPropagation()}>
              <div className="modal-header">
                <h2>📤 Send EOD Report</h2>
                <button className="modal-close" onClick={() => setShowEODModal(false)}>×</button>
              </div>
              <div className="modal-body">
                <p>Choose report format:</p>
                <div className="format-selector">
                  <label className={`format-option ${eodFormat === 'readable' ? 'selected' : ''}`}>
                    <input
                      type="radio"
                      name="eodFormat"
                      value="readable"
                      checked={eodFormat === 'readable'}
                      onChange={(e) => setEodFormat(e.target.value)}
                    />
                    <div className="format-label">
                      <strong>Readable</strong>
                      <span>With emojis and formatting</span>
                    </div>
                  </label>
                  <label className={`format-option ${eodFormat === 'monospace' ? 'selected' : ''}`}>
                    <input
                      type="radio"
                      name="eodFormat"
                      value="monospace"
                      checked={eodFormat === 'monospace'}
                      onChange={(e) => setEodFormat(e.target.value)}
                    />
                    <div className="format-label">
                      <strong>Monospace</strong>
                      <span>Plain text, compact</span>
                    </div>
                  </label>
                </div>

                <div className="report-preview">
                  <h4>Preview:</h4>
                  <pre className="preview-text">
                    {generateEODReport(eodFormat)}
                  </pre>
                </div>
              </div>
              <div className="modal-actions">
                <button className="btn-cancel" onClick={() => setShowEODModal(false)}>
                  Cancel
                </button>
                <button className="btn-primary" onClick={handleSendEOD}>
                  Send via WhatsApp
                </button>
              </div>
            </div>
          </div>
        )}
      </Suspense>
    </ErrorBoundary>
  );
}
